// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 11 Jan 2021 08:30:34 JST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "opus.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

