// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 28 Oct 2020 23:52:14 JST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "opus.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

