// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 11 Jan 2021 18:48:14 JST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package opus

/*
#cgo pkg-config: opus
#include "opus.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// Encoder as declared in opus/opus.h:164
type Encoder C.OpusEncoder

// Decoder as declared in opus/opus.h:399
type Decoder C.OpusDecoder

// Repacketizer as declared in opus/opus.h:754
type Repacketizer C.OpusRepacketizer

// Int8 type as declared in opus/opus_types.h:51
type Int8 byte

// Uint8 type as declared in opus/opus_types.h:52
type Uint8 byte

// Int16 type as declared in opus/opus_types.h:53
type Int16 int16

// Uint16 type as declared in opus/opus_types.h:54
type Uint16 uint16

// Int32 type as declared in opus/opus_types.h:55
type Int32 int32

// Uint32 type as declared in opus/opus_types.h:56
type Uint32 uint32

// Int64 type as declared in opus/opus_types.h:57
type Int64 int64

// Uint64 type as declared in opus/opus_types.h:58
type Uint64 uint64
